In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse

In [2]:
data = np.genfromtxt('../input/tracks.csv' , delimiter=',',dtype=int)[1:]

In [44]:
albums_id = data[:,1]
artists_id = data[:,2]
durations = data[:,3]
tracks = data[:,0]

In [40]:
albums_max = np.amax(albums_id)
artists_max = np.amax(artists_id)
durations_max = np.amax(durations)
number_of_songs = data.shape[0]

In [41]:
binary_matrix = sparse.lil_matrix((number_of_songs, albums_max + artists_max + durations_max + 3))

In [45]:
binary_matrix[tracks,albums_id] = 1
binary_matrix[tracks, albums_max + artists_id] = 1
binary_matrix[tracks, albums_max + artists_max + durations] = 1

In [46]:
binary_matrix

<20635x21527 sparse matrix of type '<class 'numpy.float64'>'
	with 61905 stored elements in LInked List format>

In [28]:
csr_matrix = sparse.csr_matrix(data)
print(csr_matrix.toarray())

[[    0  6306   449     0]
 [    1 12085  4903     0]
 [    2  1885  6358     6]
 ...
 [20632  8202  6200  1499]
 [20633  4789  3720  1595]
 [20634 12529    56  2114]]
