In [1]:
import scipy.sparse as sps
import numpy as np
import pandas as pd
import scipy as sc
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = np.genfromtxt('../input/train.csv' , delimiter=',',dtype=int)[1:]
playlist = data[:,0]
song = data[:,1]

data.shape

(1211791, 2)

In [3]:
unique_playlist = list(set(playlist))
unique_songs = list(set(song))

num_playlists = len(unique_playlist)
num_songs = len(unique_songs)

In [4]:
urm_all = sps.lil_matrix((num_playlists,num_songs))
urm_all[playlist,song] = 1
urm_all

<50446x20635 sparse matrix of type '<class 'numpy.float64'>'
	with 1211791 stored elements in LInked List format>

In [5]:
urm_csr = urm_all.tocsr()

In [6]:
similarities_sparse = cosine_similarity(urm_csr,dense_output=False)

In [7]:
similarities_sparse

<50446x50446 sparse matrix of type '<class 'numpy.float64'>'
	with 215922270 stored elements in Compressed Sparse Row format>

In [8]:
sim_coo = similarities_sparse.tocoo()

In [ ]:
maxi = similarities_sparse.argmax()

In [9]:
k = sim_coo.data.argmax()

In [11]:
maxval = sim_coo.data[k]

In [12]:
maxrow = sim_coo.row[k]

In [13]:
maxcol = sim_coo.col[k]

In [14]:
print('The max value is: {} , in row {} in col {}'.format(maxval,maxrow,maxcol))

The max value is: 1.0000000000000022 , in row 2152 in col 2152


In [15]:
k

8933027

In [16]:
sim_coo.data

array([ 0.2       ,  0.06523281,  0.07071068, ...,  0.03086067,
        0.03367175,  0.03984095])

In [17]:
sim_coo.row

array([    0,     0,     0, ..., 50445, 50445, 50445], dtype=int32)

In [18]:
sim_coo.col

array([49845, 49659, 46797, ...,   873,   700,   428], dtype=int32)

In [22]:
row_start = similarities_sparse.indptr[0]
row_end = similarities_sparse.indptr[1]
row_one = similarities_sparse.indices[row_start:row_end]
row_one_data = similarities_sparse.data[row_start:row_end]